style-files included, windows makefiles fixed
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/fabia@47702 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/RcppSrc/Makefile.win b/RcppSrc/Makefile.win
--- a/RcppSrc/Makefile.win
+++ b/RcppSrc/Makefile.win
@@ -2,14 +2,27 @@
 #
 # SEPP
 
-include $(R_HOME)/etc$(R_ARCH)/Makeconf
+: ${R_HOME}
+	if test -z "${R_HOME}"; then
+	   R_HOME=`${R_EXE} RHOME`		
+	fi
+	if test -z "${R_HOME}"; then
+	   R_HOME=`R RHOME`		
+	fi
+	if test -z "${R_HOME}"; then
+	    echo "Could not determine R home directory"
+	    exit 1
+	fi
+
+include ${R_HOME}/etc${R_ARCH}/Makeconf
+
 
 SRC = Rcpp.cpp
 OBJ = Rcpp.o
 LINKOBJ  = Rcpp.o $(RES)
-DLLLIBS = -s -L"$(RHOME)/$(IMPDIR)" -lR --no-export-all-symbols --add-stdcall-alias
+DLLLIBS = -s -L"${R_HOME}/$(IMPDIR)" -lR --no-export-all-symbols --add-stdcall-alias
 LIB  = libRcpp.a
-CXXFLAGS = -I"$(RHOME)/include" -I"$(RHOME)/src/include" $(CPPFLAGS) -Wall -O2
+CXXFLAGS = -I"${R_HOME}/include" -I"${R_HOME}/src/include" $(CPPFLAGS) -Wall -O2
 
 
 .PHONY: all all-before all-after clean clean-custom
@@ -23,6 +36,6 @@ $(OBJ): $(SRC)
 	$(CXX) -c $(SRC) -o $(OBJ) $(CXXFLAGS)
 	
 $(LIB): $(LINKOBJ)
-	$(AR) r $(LIB) $(OBJ)
-	$(RANLIB) $(LIB)
-	$(RM) $(OBJ)
+	${AR} r $(LIB) $(OBJ)
+	${RANLIB} $(LIB)
+	${RM} $(OBJ)
diff --git a/src/Makefile.win b/src/Makefile.win
--- a/src/Makefile.win
+++ b/src/Makefile.win
@@ -2,21 +2,33 @@
 # 
 # SEPP 
 
-include $(R_HOME)/etc$(R_ARCH)/Makeconf
+: ${R_HOME}
+	if test -z "${R_HOME}"; then
+	   R_HOME=`${R_EXE} RHOME`		
+	fi
+	if test -z "${R_HOME}"; then
+	   R_HOME=`R RHOME`		
+	fi
+	if test -z "${R_HOME}"; then
+	    echo "Could not determine R home directory"
+	    exit 1
+	fi
+
+include ${R_HOME}/etc${R_ARCH}/Makeconf
 
 
 OBJ = fabia.o
 LINKOBJ  = fabia.o $(RES)
-DLLLIBS = -s -L../RcppSrc -lRcpp  -L"$(RHOME)/$(IMPDIR)"  -lR --no-export-all-symbols --add-stdcall-alias
+DLLLIBS = -s -L../RcppSrc -lRcpp  -L"${R_HOME}/$(IMPDIR)"  -lR --no-export-all-symbols --add-stdcall-alias
 BIN  = fabia.dll
-CXXFLAGS = -I../RcppSrc -I"$(RHOME)/include" -Wall -O2 -DBUILDING_DLL=1
+CXXFLAGS = -I../RcppSrc -I"${R_HOME}/include" -Wall -O2 -DBUILDING_DLL=1
 
 .PHONY: all clean
 
 all: fabia.dll
 
 clean:
-	$(RM) $(LINKOBJ) $(BIN)
+	${RM} $(LINKOBJ) $(BIN)
 
 $(BIN): $(LINKOBJ)
 	$(CXX) -shared $(LINKOBJ) $(DLLLIBS) -o $(BIN)
